/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_ANOMALY_METADATA_H_
#define _EI_CLASSIFIER_ANOMALY_METADATA_H_

#include "edge-impulse-sdk/classifier/ei_model_types.h"

const uint16_t ei_classifier_anom_axes_1001587_7[] = { 0, 13, 26 };

// (before - mean) / scale
const float ei_classifier_anom_scale_1001587_7[3] = { 1.0000000097843245, 0.9999999815512607, 0.9999999873872614 };
const float ei_classifier_anom_mean_1001587_7[3] = { -2.2946372993436514e-9, -3.4007730778136286e-9, 5.8409295294409485e-9 };
const ei_classifier_anom_cluster_t ei_classifier_anom_clusters_1001587_7[32] = {
	{ ( float[3] ) { -1.193993091583252, 0.07688084244728088, -0.4385444223880768 }, 0.37720498314478335 },
	{ ( float[3] ) { -1.191927194595337, -0.26931703090667725, -0.44726651906967163 }, 0.3068387952089016 },
	{ ( float[3] ) { 1.0071685314178467, 2.1163716316223145, -0.4074847400188446 }, 0.8675210543898751 },
	{ ( float[3] ) { 1.1623139381408691, -0.7010267376899719, -0.4123642146587372 }, 0.5693219635709055 },
	{ ( float[3] ) { 0.6990072727203369, -1.0472710132598877, 0.4193198084831238 }, 0.6303497951492021 },
	{ ( float[3] ) { 0.4349689781665802, -0.15095524489879608, -0.4674241542816162 }, 0.7764377926834368 },
	{ ( float[3] ) { 0.8593586087226868, -0.7604524493217468, 2.910008668899536 }, 0.8628517013352346 },
	{ ( float[3] ) { 0.07424183189868927, 0.6038823127746582, -0.43989312648773193 }, 0.5105811889433872 },
	{ ( float[3] ) { 0.07146121561527252, -0.4318200647830963, -0.4199643135070801 }, 0.5412701498757233 },
	{ ( float[3] ) { 2.0176448822021484, -1.0094287395477295, 0.06099759042263031 }, 0.5278153213530085 },
	{ ( float[3] ) { -0.043741993606090546, -0.9067999124526978, 2.7863802909851074 }, 0.7439852877706236 },
	{ ( float[3] ) { -1.1906667947769165, 0.6664266586303711, -0.4488668143749237 }, 0.40493192915232035 },
	{ ( float[3] ) { -0.0705251470208168, 0.045228686183691025, -0.37028950452804565 }, 0.4443181726870093 },
	{ ( float[3] ) { 0.5258446335792542, 1.2747187614440918, -0.31841209530830383 }, 0.6921899420453335 },
	{ ( float[3] ) { 1.7387930154800415, 1.6345120668411255, 3.788327932357788 }, 0.6263304450485511 },
	{ ( float[3] ) { 0.9628976583480835, 3.1473069190979004, -0.43958890438079834 }, 0.6144424257096806 },
	{ ( float[3] ) { 2.579801559448242, 2.6278481483459473, 2.841938018798828 }, 0.5600471121722097 },
	{ ( float[3] ) { 0.5028394460678101, -0.9479520916938782, -0.7589303851127625 }, 0.7729839407792236 },
	{ ( float[3] ) { 0.08781825006008148, -0.41379308700561523, 0.7538381814956665 }, 0.57694922978758 },
	{ ( float[3] ) { 0.7455700039863586, -0.7604324817657471, 7.2617692947387695 }, 0 },
	{ ( float[3] ) { 1.9292628765106201, 0.32665058970451355, -0.4375668168067932 }, 1.02701048982983 },
	{ ( float[3] ) { 0.9295921325683594, 0.31823107600212097, -0.36775633692741394 }, 0.4489744177658488 },
	{ ( float[3] ) { -1.1198699474334717, 4.012889862060547, -0.3319963812828064 }, 0.6157753580720986 },
	{ ( float[3] ) { 0.09303988516330719, -0.9353448748588562, 0.8901255130767822 }, 0.8113089019141957 },
	{ ( float[3] ) { -0.12174314260482788, -0.9588109254837036, 0.07292400300502777 }, 0.6173773940474023 },
	{ ( float[3] ) { 0.19129899144172668, -0.5700250267982483, 4.605245113372803 }, 1.031454113797381 },
	{ ( float[3] ) { 0.9830549955368042, -0.7200949192047119, 1.573116421699524 }, 0.9850152150911143 },
	{ ( float[3] ) { 0.34175440669059753, -1.1247369050979614, 1.6330554485321045 }, 0.530423465145314 },
	{ ( float[3] ) { 2.0758678913116455, -1.0548357963562012, 2.1290924549102783 }, 0.6471332827700969 },
	{ ( float[3] ) { 1.3772704601287842, -0.34465479850769043, 0.6900398135185242 }, 0.7037404805488837 },
	{ ( float[3] ) { 2.6763644218444824, 3.6183817386627197, 5.228231430053711 }, 0 },
	{ ( float[3] ) { -1.192736268043518, 5.597403049468994, -0.5503951907157898 }, 0 },
};

#endif // _EI_CLASSIFIER_ANOMALY_METADATA_H_
