/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"
#include "anomaly_metadata.h"
#include "tflite-model/tflite_learn_1001587_5_compiled.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_1001587_1[] = { "Idle", "Updown", "Waving" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_1001587_3_axes[] = { 0, 1, 2 };
const uint32_t ei_dsp_config_1001587_3_axes_size = 3;
ei_dsp_config_spectral_analysis_t ei_dsp_config_1001587_3 = {
    3, // uint32_t blockId
    4, // int implementationVersion
    3, // int length of axes
    1.0f, // float scale-axes
    1, // int input-decimation-ratio
    "low", // select filter-type
    8.0f, // float filter-cutoff
    6, // int filter-order
    "FFT", // select analysis-type
    64, // int fft-length
    3, // int spectral-peaks-count
    0.1f, // float spectral-peaks-threshold
    "0.1, 0.5, 1.0, 2.0, 5.0", // string spectral-power-edges
    true, // boolean do-log
    true, // boolean do-fft-overlap
    1, // int wavelet-level
    "db4", // select wavelet
    false // boolean extra-low-freq
};

const float ei_dn_standard_scaler_mean_1001587_3[33] = { 679.5286532632666, 1.2244547500672258, 6.450319033166701, 2.873283262930664, 8.072770358300676, 6.7808959413977234, 6.6495521201027765, 6.48914293136472, 6.328154873224645, 6.156072858891456, 5.849007942318138, 384.10034859102535, 0.21888218487567154, 0.10311068673768413, 3.1502392765353706, 10.219950955385476, 5.685347168274175, 5.467096864398009, 5.3037168410868425, 5.20052513071135, 5.10340069867427, 4.849421242483301, 3065.9669337054484, -4.081206273409276, 16.980153853597205, 2.199388220224505, 3.6704056496713675, 8.217244170070474, 8.17413463467866, 8.111114585321713, 8.013938506444296, 7.816442856601641, 7.322694317188138 };
const float ei_dn_standard_scaler_scale_1001587_3[33] = { 0.0031385915050107364, 0.4618459974670266, 0.12483071731179066, 1.2809263775875277, 0.18446288545952685, 2.0950495584568105, 2.3052066032304848, 2.543578405261493, 2.6745801849359205, 2.4682419007424423, 1.974322249066008, 0.002494780629362518, 1.9940745315638264, 0.7962266422211723, 0.9768285626403224, 0.13817426703463884, 0.7599448320326632, 0.8993672570259035, 0.9732115847298212, 1.0706040264528085, 1.117053705634223, 1.1250976775709267, 0.006291652158351925, 1.6481691487931518, 0.2895690372304956, 3.4686944937681963, 0.5202009068733259, 9.565130563111236, 11.66026840561513, 16.516728623528532, 17.386397738436713, 16.841060071738056, 12.396863799025839 };
const float ei_dn_standard_scaler_var_1001587_3[33] = { 101515.04468336211, 4.688194613689939, 64.17369824229542, 0.6094690581486081, 29.388810219490068, 0.22783025626483216, 0.18818295769796686, 0.15456449581906345, 0.1397940717027368, 0.16414382853226547, 0.25654521608925973, 160670.17745327306, 0.2514879765575051, 1.5773446224496699, 1.04800486824684, 52.37760800180329, 1.7315533148729554, 1.2363056539723776, 1.0558092439698248, 0.872453431645398, 0.8014047141905447, 0.7899862704970957, 25262.166416911958, 0.3681259550920328, 11.926026105483412, 0.0831127970510488, 3.6953688196987784, 0.01092995049831151, 0.007355003860750344, 0.003665657915906815, 0.0033081163746921704, 0.003525828224813488, 0.006506933082962118 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_1001587_3 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_1001587_3,
    .mean_data_len = 33,
    .scale_data = (float *)ei_dn_standard_scaler_scale_1001587_3,
    .scale_data_len = 33,
    .var_data = (float *)ei_dn_standard_scaler_var_1001587_3,
    .var_data_len = 33
};
ei_data_normalization_t ei_data_normalization_config_1001587_3 = {
    (void *) &ei_data_normalization_standard_scaler_config_1001587_3, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};

const uint8_t ei_dsp_blocks_1001587_1_size = 1;
ei_model_dsp_t ei_dsp_blocks_1001587_1[ei_dsp_blocks_1001587_1_size] = {
    { // DSP block 3
        3,
        33, // output size
        &extract_spectral_analysis_features, // DSP function pointer
        (void*)&ei_dsp_config_1001587_3, // pointer to config struct
        ei_dsp_config_1001587_3_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_1001587_3_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        &ei_data_normalization_config_1001587_3, // data normalization config
    }
};
const ei_config_tflite_eon_graph_t ei_config_graph_1001587_5 = {
    .implementation_version = 1,
    .model_init = &tflite_learn_1001587_5_init,
    .model_invoke = &tflite_learn_1001587_5_invoke,
    .model_reset = &tflite_learn_1001587_5_reset,
    .model_input = &tflite_learn_1001587_5_input,
    .model_output = &tflite_learn_1001587_5_output,
};

const uint8_t ei_output_tensors_indices_1001587_5[1] = { 0 };
const uint8_t ei_output_tensors_size_1001587_5 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_1001587_5 = {
    .implementation_version = 1,
    .block_id = 5,
    .output_tensors_indices = ei_output_tensors_indices_1001587_5,
    .output_tensors_size = ei_output_tensors_size_1001587_5,
    .quantized = 1,
    .compiled = 1,
    .graph_config = (void*)&ei_config_graph_1001587_5,
    .dequantize_output = 0,
};

const ei_learning_block_config_anomaly_kmeans_t ei_learning_block_config_1001587_7 = {
    .implementation_version = 1,
    .block_id = 7,
    .anom_axis = ei_classifier_anom_axes_1001587_7,
    .anom_axes_size = 3,
    .anom_clusters = ei_classifier_anom_clusters_1001587_7,
    .anom_cluster_count = 32,
    .anom_scale = ei_classifier_anom_scale_1001587_7,
    .anom_mean = ei_classifier_anom_mean_1001587_7,
};

const uint8_t ei_learning_blocks_1001587_1_size = 2;
const uint32_t ei_learning_block_1001587_5_inputs[1] = { 3 };
const uint8_t ei_learning_block_1001587_5_inputs_size = 1;
const uint32_t ei_learning_block_1001587_7_inputs[1] = { 3 };
const uint8_t ei_learning_block_1001587_7_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_1001587_1[ei_learning_blocks_1001587_1_size] = {
    {
        5,
        &run_nn_inference,
        (void*)&ei_learning_block_config_1001587_5,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_1001587_5_inputs,
        ei_learning_block_1001587_5_inputs_size,
    },
    {
        7,
        &run_kmeans_anomaly,
        (void*)&ei_learning_block_config_1001587_7,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_1001587_7_inputs,
        ei_learning_block_1001587_7_inputs_size,
    },
};

ei_fill_result_classification_i8_config_t ei_fill_result_classification_i8_config_1001587_5 = {
    .zero_point = -128,
    .scale = 0.00390625
};

const size_t ei_postprocessing_blocks_1001587_1_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_1001587_1[ei_postprocessing_blocks_1001587_1_size] = {
    {
        .block_id = 5,
        .type = EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_i8,
        .display_fn = NULL,
        .config = (void*)&ei_fill_result_classification_i8_config_1001587_5,
        .input_block_id = 5
    },
};

const uint8_t freeform_outputs_1001587_1_size = 0;

uint32_t *freeform_outputs_1001587_1 = nullptr;

const ei_impulse_t impulse_1001587_1 = {
    .project_id = 1001587,
    .project_owner = "Maria_Eduarda_Santos",
    .project_name = "Maria_Eduarda_Santos-project-1",
    .impulse_id = 1,
    .impulse_name = "Impulse #1",
    .deploy_version = 1,

    .nn_input_frame_size = 33,
    .raw_sample_count = 168,
    .raw_samples_per_frame = 3,
    .dsp_input_frame_size = 168 * 3,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 11.904761904761905,
    .frequency = 84,

    .dsp_blocks_size = ei_dsp_blocks_1001587_1_size,
    .dsp_blocks = ei_dsp_blocks_1001587_1,

    .learning_blocks_size = ei_learning_blocks_1001587_1_size,
    .learning_blocks = ei_learning_blocks_1001587_1,

    .postprocessing_blocks_size = ei_postprocessing_blocks_1001587_1_size,
    .postprocessing_blocks = ei_postprocessing_blocks_1001587_1,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "x + y + z",
    .slice_size = (168/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_KMEANS,
    .label_count = 3,
    .categories = ei_classifier_inferencing_categories_1001587_1,
    .results_type = EI_CLASSIFIER_TYPE_CLASSIFICATION,
    .freeform_outputs_size = freeform_outputs_1001587_1_size,
    .freeform_outputs = freeform_outputs_1001587_1
};

ei_impulse_handle_t impulse_handle_1001587_1 = ei_impulse_handle_t( &impulse_1001587_1 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_1001587_1;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_1001587_1;
const auto ei_dsp_blocks_size = ei_dsp_blocks_1001587_1_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_1001587_1;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
